### ISSUE TITLE
Unit test failing on windows

### ISSUE THREAD

**Issue by Vatavuk** [driver733/VK-Uploader#383]
This unit test fails when executing `mvn clean test` on windows machine. Test is passing on OSX though.
First execution:
```
test(com.driver733.vkuploader.wallpost.WallPostMusicAlbumTest)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.AssertionError:
Incorrect query map produced.
Expected: (map containing ["access_token"->"1"] and map containing ["v"->"5.63"] and map containing ["attachments"->"photo6785_123456,audio-161929264_123456789"] and map containing ["owner_id"->"-161929264"] and map containing ["from_group"->"1"] and map containing ["message"->"Album: Elegant Testing\nArtist: Test Man"])
     but: map containing ["message"->"Album: Elegant Testing\nArtist: Test Man"] map was [<access_token=1>, <attachments=photo6785_123456,audio-161929264_123456789>, <v=5.63>, <owner_id=-161929264>, <from_group=1>, <message=Album: Elegant Testing
Artist: Test Man>]
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.driver733.vkuploader.wallpost.WallPostMusicAlbumTest.test(WallPostMusicAlbumTest.java:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Second attempt:
```
<<< FAILURE! - in com.driver733.vkuploader.wallpost.WallPostMusicAlbumTest
test(com.driver733.vkuploader.wallpost.WallPostMusicAlbumTest)  Time elapsed: 0.203 sec  <<< ERROR!
java.lang.IllegalStateException: PropertiesUpdate key not found
        at com.driver733.vkuploader.wallpost.attachment.support.PropertiesUpdate.run(PropertiesUpdate.java:104)
        at com.driver733.vkuploader.wallpost.attachment.support.fields.AttachmentArraysWithProps.attachmentsFields(AttachmentArraysWithProps.java:134)
        at com.driver733.vkuploader.wallpost.WallPostWithAttachments.construct(WallPostWithAttachments.java:74)
        at com.driver733.vkuploader.wallpost.WallPostWithMessage.construct(WallPostWithMessage.java:84)
        at com.driver733.vkuploader.wallpost.WallPostFromGroup.construct(WallPostFromGroup.java:56)
        at com.driver733.vkuploader.wallpost.WallPostWithOwnerId.construct(WallPostWithOwnerId.java:63)
        at com.driver733.vkuploader.wallpost.WallPostMusicAlbum.construct(WallPostMusicAlbum.java:206)
        at com.driver733.vkuploader.wallpost.WallPostMusicAlbumTest.test(WallPostMusicAlbumTest.java:241)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Key not found.
        at com.driver733.vkuploader.wallpost.attachment.support.PropertiesUpdate.key(PropertiesUpdate.java:141)
        at com.driver733.vkuploader.wallpost.attachment.support.PropertiesUpdate.run(PropertiesUpdate.java:92)
        ... 25 more
```

**Comment by driver733** [comment]
Fixed in https://github.com/driver733/VK-Uploader/runs/716132425?check_suite_focus=true
